### ISSUE TITLE
Replace platform parameter with the target_device parameter

### ISSUE THREAD

**Issue by brian-intel** [intel-retail/documentation#5]
# Replace platform parameter with the target_device parameter

- [Status](#status)
- [Decision](#decision)
- [Context](#context)
- [Proposed Design](#proposed-design)
- [Consequences](#consequences)
- [References](#references)

## Status

New

## Context  

The platform parameter is inconsistent with the target device being used in the pipeline. To be consistent with OVMS we want to use the target_device parameter in the script to match the target_device setting in the OVMS config file.

## Proposed Design 

- Replace platform parameter with target_device using CPU as the default device.
- Update DLStreamer docker_run script to make it run with minimal updates to the DLStreamer scripts.
- Update the OVMS docker_run script to make it run with minimal changes to the OVMS profiles.
- Confirm that the benchmark script works with the target_device parameter update.
- Update unit tests
- Update documentation
- Convert $DEVICE to $TARGET_DEVICE for internal environment variables.
- Add option to use existing config file and not override all target_devices to support models with different target_device values.

## Applicable Repos

[automated-self-checkout](https://github.com/intel-retail/automated-self-checkout)

## Consequences

Removing the platform parameter will break any existing test and benchmark scripts. The change will clarify which device you are targeting for the inference.

## References

[platform parameter](https://github.com/intel-retail/automated-self-checkout/blob/main/get-options.sh#L51)

**Comment by jim-wang-intel** [comment]
A note from today's DSU:  In order to use DGPU.x in the DEVICE env; we should mount all devices instead of selectively mount
